### ISSUE TITLE
Running the grid_search.py from different directory cannot pickup config.yaml

### ISSUE THREAD

**Issue by KPHippe** [braceal/ot2util#15]
If run the grid_search.py from a different directory (not in `examples/basic_protocol/`) then the script cannot find `config.yaml`

command:  
```python ../examples/basic_protocol/grid_search.py -c ../examples/basic_protocol/grid_search.yaml```
run from `ot2util/ot2util/`

Error: 
```
Traceback (most recent call last):
  File "/home/kyle/Documents/School/Auto_Labs/ot2util/ot2util/../examples/basic_protocol/grid_search.py", line 90, in <module>
    main(cfg)
  File "/home/kyle/Documents/School/Auto_Labs/ot2util/ot2util/../examples/basic_protocol/grid_search.py", line 52, in main
    protocol_cfg = SimpleProtocolConfig.from_yaml("config.yaml")
  File "/home/kyle/Documents/School/Auto_Labs/ot2util/ot2util/config.py", line 20, in from_yaml
    with open(filename) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
```

Might have to include some path logic for finding the protocol in the same dir as the protocol?

**Comment by braceal** [comment]
Yeah this is to initialize the base protocol config used for common settings like the equipment types. Let me add a option to specify this config file in the grid_search.yaml

**Comment by braceal** [comment]
Since it was just a small change and it didn't impact the interface, I just pushed directly to main. Should be fixed.
