### ISSUE TITLE
Fabric for sending jobs over ssh

### ISSUE THREAD

**Issue by braceal** [braceal/ot2util#2]
We might try to use Fabric for communicating with the pi over ssh. Then we could run more computationally demanding search strategies. We are currently limited to the compute power on the pi.

The search agent could generate experiment configs locally (or on a cluster), and then send them to the pi using Fabric, then send back the stdout, stderr, and experiment results to the search agent. 

This could be handled by the ExperimentManager class, we can expose ip and port arguments.

https://docs.fabfile.org/en/1.12.1/tutorial.html

**Comment by KPHippe** [comment]
As a side note, I do not think we need to raise an exception if the key_filename is none. I have tested it on my machines and it works as long as the default private key in ~/.ssh folder is the one used for access to the remote host. Maybe we wrap in try/except if it fails and say the user would need to provide a key then? Just a small note

**Comment by braceal** [comment]
Oh nice, thanks for testing! It sounds like we could make it an optional parameter, in case a user makes a key that is not the default one. So the behavior would be: If host is not None, check if a key_filename is present, otherwise use the default private key. 

On a separate note, we can also add two optional fields in the configuration which allow users to run custom commands on the OT-2 before and after execution of the experiment. We can call them `pre_exec` and `post_exec` and they would both be of type `List[str]`. This should add in some flexibility. 

Another thing to look at is the latency of using many connection.run() calls versus grouping the calls together. There might be some performance optimization we can do there.

**Comment by legendPerceptor** [comment]
Current error:
```
python grid_search.py -c grid_search.yaml 
Traceback (most recent call last):
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/sftp_client.py", line 130, in __init__
    server_version = self._send_version()
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/sftp.py", line 134, in _send_version
    t, data = self._read_packet()
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/sftp.py", line 201, in _read_packet
    x = self._read_all(4)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/sftp.py", line 188, in _read_all
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Development/ot2util/examples/basic_protocol/grid_search.py", line 70, in <module>
    main(cfg)
  File "/Users/apple/Development/ot2util/examples/basic_protocol/grid_search.py", line 64, in main
    experiment_manager.run(experiment)
  File "/Users/apple/Development/ot2util/ot2util/experiment.py", line 128, in run
    return self._run_remote(experiment)
  File "/Users/apple/Development/ot2util/ot2util/experiment.py", line 86, in _run_remote
    self.conn.put(experiment.protocol_script, remote=workdir)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/fabric/connection.py", line 870, in put
    return Transfer(self).put(*args, **kwargs)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/fabric/transfer.py", line 255, in put
    elif self.is_remote_dir(remote):
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/fabric/transfer.py", line 42, in is_remote_dir
    return stat.S_ISDIR(self.sftp.stat(path).st_mode)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/fabric/transfer.py", line 38, in sftp
    return self.connection.sftp()
  File "<decorator-gen-6>", line 2, in sftp
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/fabric/connection.py", line 847, in sftp
    self._sftp = self.client.open_sftp()
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/client.py", line 558, in open_sftp
    return self._transport.open_sftp_client()
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/transport.py", line 1097, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/sftp_client.py", line 170, in from_transport
    return cls(chan)
  File "/Users/apple/Development/ot2util/env/lib/python3.9/site-packages/paramiko/sftp_client.py", line 132, in __init__
    raise SSHException("EOF during negotiation")
paramiko.ssh_exception.SSHException: EOF during negotiation
```

**Comment by legendPerceptor** [comment]
Make tarring optional

**Comment by braceal** [comment]
Fabric connection works for a single machine. Closing the issue.
